### ISSUE TITLE
Class 13: Deploy to Heroku Checklist

### ISSUE THREAD

**Issue by risachi** [risachi/code-blog#10]
- [x] create server.js
- [x] run "npm install" to generate node_modules
- [x] "npm install express"
- [x] "npm install express-request-proxy"
- [x] create package.json
- [x] create .gitignore
- [x] create .env
- [x] create Procfile
- [x] [go through heroku tutorial to create a new app](https://devcenter.heroku.com/articles/getting-started-with-nodejs#introduction)
- [x] scale up dynos
- [x] set up GITHUB_TOKEN (config) on heroku

**Comment by risachi** [comment]
create server.js, copy and paste:

```
var requestProxy = require('express-request-proxy'),
  express = require('express'),
  port = process.env.PORT || 3000,
  app = express();

var proxyGitHub = function(request, response) {
  console.log('Routing GitHub request for', request.params[0]);
  (requestProxy({
    url: 'https://api.github.com/' + request.params[0],
    headers: { Authorization: 'token ' + process.env.GITHUB_TOKEN }
  }))(request, response);
};

app.get('/github/*', proxyGitHub);

app.use(express.static('./'));

app.get('*', function(request, response) {
  console.log('New request:', request.url);
  response.sendFile('index.html', { root: '.' });
});

app.listen(port, function() {
  console.log('Server started on port ' + port + '!');
});
```

**Comment by risachi** [comment]
create package.json, copy and paste:

```
{
  "name": "mvc-blog",
  "version": "1.0.0",
  "description": "As we now complete our MVC conversation, we can refactor our app to use good MVC separation of concerns.",
  "main": "server.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Code Fellows",
  "license": "ISC",
  "dependencies": {
    "express": "^4.13.3",
    "express-request-proxy": "^1.0.10"
  }
}
```

**Comment by risachi** [comment]
create .gitignore to ignore the `node_modules/*`

**Comment by risachi** [comment]
the .env file holds `var GITHUB_TOKEN = [insert github token]`

**Note: this step is redundant if you use `heroku config:set GITHUB_TOKEN=[insert github token here]` below**

**Comment by risachi** [comment]
Procfile tells Heroku where to look, input:
`web: node server.js`

**Comment by risachi** [comment]
Main points of the Heroku tutorial (type into the command line):
- `heroku apps:create [insert desired name of app here]` creates a new Heroku app with the name you've chosen
- `heroku config:set GITHUB_TOKEN=[insert github token here]` so that Heroku can access your Github token when it needs to
- `git push heroku class-13:master` links Github and Heroku together. "class-13" is your Github branch; "master" is Heroku's branch. If your app is pushed to master in Github, then the command is `git push heroku master`
- `heroku ps:scale web=1` scales up dynos
- `git remote -v` checks the Github-Heroku love link
- add and commit any changes to your code

To test:
- `heroku open` opens your app served by Heroku
- `node server.js` opens your app locally
